name: PR Builder

on:
  pull_request:
    branches: [main, asgardeo]

jobs:
  setup-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [app]

    defaults:
      run:
        working-directory: ${{ matrix.app }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Frontend application
        run: npm run build
